const PDFDocument = require('pdfkit');

const generateResolutionPDF = (issue, updates, reportText) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill('#1e3a5f');
    doc.fillColor('white').fontSize(22).font('Helvetica-Bold')
      .text('Smart City Issue Resolution Report', 50, 25, { align: 'center' });

    doc.moveDown(3);

    // Issue Details Box
    doc.fillColor('#1e3a5f').fontSize(14).font('Helvetica-Bold').text('Issue Details', 50, 100);
    doc.moveTo(50, 118).lineTo(545, 118).strokeColor('#1e3a5f').stroke();

    doc.fillColor('#333').fontSize(11).font('Helvetica');
    const details = [
      ['Issue ID', issue.id.substring(0, 8).toUpperCase()],
      ['Title', issue.title],
      ['Category', issue.category],
      ['Priority', issue.priority],
      ['Status', issue.status],
      ['Location', `${issue.lat.toFixed(4)}, ${issue.lng.toFixed(4)}`],
      ['Area', issue.area || 'N/A'],
      ['Reported On', new Date(issue.createdAt).toLocaleDateString('en-IN', { dateStyle: 'long' })],
      ['Resolved On', issue.resolvedAt ? new Date(issue.resolvedAt).toLocaleDateString('en-IN', { dateStyle: 'long' }) : 'Pending'],
    ];

    let y = 130;
    details.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').fillColor('#555').text(`${label}:`, 50, y, { width: 120 });
      doc.font('Helvetica').fillColor('#333').text(value, 175, y, { width: 370 });
      y += 20;
    });

    // Response Time
    if (issue.resolvedAt) {
      const hours = Math.round((new Date(issue.resolvedAt) - new Date(issue.createdAt)) / 3600000);
      doc.font('Helvetica-Bold').fillColor('#555').text('Response Time:', 50, y, { width: 120 });
      doc.font('Helvetica').fillColor('#333').text(`${hours} hours`, 175, y);
      y += 20;
    }

    y += 20;

    // Description
    doc.fillColor('#1e3a5f').fontSize(14).font('Helvetica-Bold').text('Description', 50, y);
    doc.moveTo(50, y + 18).lineTo(545, y + 18).strokeColor('#1e3a5f').stroke();
    y += 28;
    doc.fillColor('#333').fontSize(11).font('Helvetica').text(issue.description, 50, y, { width: 495 });

    y = doc.y + 25;

    // Resolution Report
    doc.fillColor('#1e3a5f').fontSize(14).font('Helvetica-Bold').text('Resolution Summary', 50, y);
    doc.moveTo(50, y + 18).lineTo(545, y + 18).strokeColor('#1e3a5f').stroke();
    y += 28;
    doc.fillColor('#333').fontSize(11).font('Helvetica').text(reportText, 50, y, { width: 495 });

    y = doc.y + 25;

    // Status Timeline
    if (updates && updates.length > 0) {
      doc.fillColor('#1e3a5f').fontSize(14).font('Helvetica-Bold').text('Status Timeline', 50, y);
      doc.moveTo(50, y + 18).lineTo(545, y + 18).strokeColor('#1e3a5f').stroke();
      y += 30;

      updates.forEach((update) => {
        const statusColors = {
          REPORTED: '#6b7280',
          IN_REVIEW: '#3b82f6',
          IN_PROGRESS: '#f59e0b',
          RESOLVED: '#10b981',
          REJECTED: '#ef4444',
        };
        const color = statusColors[update.status] || '#333';

        doc.circle(60, y + 5, 5).fill(color);
        doc.font('Helvetica-Bold').fillColor(color).fontSize(10)
          .text(update.status.replace('_', ' '), 75, y - 2);
        doc.font('Helvetica').fillColor('#666').fontSize(9)
          .text(new Date(update.createdAt).toLocaleString('en-IN'), 75, y + 10);
        if (update.note) {
          doc.font('Helvetica').fillColor('#333').fontSize(10)
            .text(update.note, 75, y + 22, { width: 460 });
        }
        y += 50;
      });
    }

    // Footer
    doc.fontSize(9).fillColor('#999').font('Helvetica')
      .text(
        `Generated by Smart City Platform • ${new Date().toLocaleString('en-IN')} • Confidential`,
        50,
        doc.page.height - 40,
        { align: 'center', width: 495 }
      );

    doc.end();
  });
};

module.exports = { generateResolutionPDF };
